// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924213000_VoegAangemaaktOpToe")]
    partial class VoegAangemaaktOpToe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
