// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902160000_VoegAgendaToe")]
    partial class VoegAgendaToe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
