// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831100000_VoegFactuurVeldenToe")]
    partial class VoegFactuurVeldenToe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
